# Site settings
title: "#sbhackerspace"
description: "The world's greatest hackerspace in Santa Barbara"
url: "http://sbhackerspace.com"
email: info@sbhackerspace.com

keywords: "Santa Barbara Hackerspace, Hackerspace, Makerspace, SBHX, Builders, Makers, Make, Open-Source, DIY, Workshop, Electronics, Tracksoar"
twitter_username: sbhackerspace
github_username:  sbhackerspace

# Output
permalink: "/:year/:month/:day/:title/"
timezone: America/Los_Angeles

# Build settings
markdown: kramdown

# SEO
twitter:
    username: sbhackerspace
